### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by 7heMech** [lau1944/bunrest#24] opened 2023-09-15 13:43 UTC
I don't have a get route defined at /, but I do have
```js
app.use((req, res, next, err) => {
  res.status(404).send('Not found');
});
```
So why is the app throwing  an error, is this intentional?
```sh
189 |         // fix (issue 4: unhandle route did not throw an error)
190 |         if (!handlers || handlers.length === 0) {
191 |           throw new Error(`Cannot ${req.method} ${req.path}`);
                    ^
error: Cannot GET /
      at /home/runner/test/node_modules/bunrest/src/server/server.ts:191:16

189 |         // fix (issue 4: unhandle route did not throw an error)
190 |         if (!handlers || handlers.length === 0) {
191 |           throw new Error(`Cannot ${req.method} ${req.path}`);
                    ^
error: Cannot GET /favicon.ico
      at /home/runner/test/node_modules/bunrest/src/server/server.ts:191:16
```

**Comment by lau1944** [comment] 2023-09-15 15:35
fixed. Upgrade version to `bunrest@1.3.1`

**Comment by lau1944** [comment] 2023-09-16 01:50
I cannot reproduce the issue, provide more context. Like what version your bun is on? what is your sample code

**Comment by lau1944** [comment] 2023-09-17 03:16
> ```js
> import server from "bunrest";
> const app = server();
> 
> app.use((req, res, next, err) => {
>   res.status(404).send('Not found');
> });
> 
> app.listen(8080, () => console.log('Server listening on port 8080!'));
> ```

Upgrade to the latest version `1.3.5`

```
curl -X GET http://localhost:8080
```
You are using global error handle here, you should see a `Not found` response, but also an error will be logged in your server.

If you want to use a normal middleware, just remove the `err` in the last argument.

**Comment by lau1944** [comment] 2023-09-17 03:18
> @lau1944 I don't think the type error is from you, it happens when you do `new URL(req.url);` I'm getting this as a first request from the proxy of my webserver:
> 
> ```js
> Request (0 KB) {
>   method: "OPTIONS",
>   url: "*",
>   headers: Headers {
>     "host": "10.20.1.200:16854",
>     "user-agent": "Go-http-client/1.1",
>     "accept-encoding": "gzip"
>   }
> }
> ```
> 
> Adding this before parse fixed it:
> 
> ```js
> if (req.url === "*") return;
> ```

I think `OPTIONS` method is missing in `bun`, you can submit an issue to bun but I won't fix it here since it's just a library, I cannot change the behavior in my code just to adapter the issue from bun.

**Comment by lau1944** [comment] 2023-09-17 09:35
> @lau1944 it is not missing, I'm able to get proper options requests with url, this * thing only happens from the reverse proxy on the hosting servers, it's probably just telling me the settings for all requests or sth.

If it's that case, you should properly configure your request header on your proxy. Request url should always be in URL format, no matter the problem is on proxy or bun.

**Closed** 2023-09-18 11:22 UTC
